# Generated by Django 4.2.7 on 2024-02-09 14:38

import bboard.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[(None, 'Выберите тип объявления'), ('b', 'Куплю'), ('s', 'Продам'), ('r', 'Аренда'), ('p', 'Дар')], default='s', max_length=1)),
                ('title', models.CharField(error_messages={'invalid': 'Зачем вводишь некорректные данные?'}, max_length=50, validators=[django.core.validators.RegexValidator(regex='^.{4,}$')], verbose_name='Товар')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[bboard.models.validate_even], verbose_name='Цена')),
                ('is_active', models.BooleanField(default=False)),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Опубликовано')),
                ('feature', models.CharField(choices=[('n', 'Новый'), ('u', 'Б\\у'), ('o', 'Под заказ')], default='u', max_length=1, verbose_name='Свойство')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Название')),
                ('order', models.SmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_creator', models.CharField(max_length=30, verbose_name='Автор')),
                ('comment', models.CharField(max_length=500, verbose_name='Комментарий')),
                ('issue_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('bb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.bb', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.AddField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.rubric', verbose_name='Рубрика'),
        ),
    ]
