# Generated by Django 4.2.7 on 2024-02-20 15:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bb',
            managers=[
                ('by_price', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='rubric',
            managers=[
                ('bbs', django.db.models.manager.Manager()),
            ],
        ),
    ]
