# Generated by Django 4.2.7 on 2023-12-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='kind',
            field=models.CharField(choices=[(None, 'Выберите тип объявления'), ('b', 'Куплю'), ('s', 'Продам'), ('r', 'Аренда'), ('p', 'Дар')], default='s', max_length=1),
        ),
    ]
