# Generated by Django 4.2.7 on 2023-12-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_bb_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='feature',
            field=models.CharField(choices=[('n', 'Новый'), ('u', 'Б\\у'), ('o', 'Под заказ')], default='u', max_length=1, verbose_name='Свойство'),
        ),
    ]
