# Generated by Django 4.2.7 on 2023-12-19 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_alter_bb_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_creator', models.CharField(max_length=30, verbose_name='Автор объявления')),
                ('comment', models.CharField(max_length=500, verbose_name='Комментарий')),
                ('issue_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('bb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bboard.bb', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-issue_date'],
            },
        ),
    ]
