# Generated by Django 4.2.7 on 2023-12-24 13:26

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='feature',
            field=models.CharField(choices=[('n', 'Новый'), ('u', 'Б\\у'), ('o', 'Под заказ')], default='u', max_length=1, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[bboard.models.validate_even], verbose_name='Цена'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
