# Generated by Django 4.2.7 on 2024-01-13 19:02

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[bboard.models.validate_even], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_creator',
            field=models.CharField(max_length=30, verbose_name='Автор'),
        ),
    ]
