# Generated by Django 4.2.7 on 2023-12-03 10:37

import accounts.models
import django.contrib.auth.password_validation
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30, unique=True, validators=[accounts.models.PassValidator, django.contrib.auth.password_validation.CommonPasswordValidator])),
                ('email', models.CharField(error_messages={'invalid': 'Введите корректный адрес электронной почты'}, max_length=30, unique=True, validators=[django.core.validators.RegexValidator(regex='\\w[\\w\\.-]*\\w+@\\w[\\w\\.]*\\.[a-zA-Z]{2,3}')])),
                ('birth_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['pk'],
            },
        ),
    ]
