# Generated by Django 4.2.7 on 2023-12-03 11:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clients',
            name='password',
            field=models.CharField(max_length=30, unique=True, validators=[accounts.models.PassValidator]),
        ),
    ]
